name: getinplay

services:

  frontend:
    build: ./getinplay_react
    ports:
      - 80:5173
    restart: unless-stopped
    depends_on:
      php-env:
        condition: service_healthy
      mariadb_db:
        condition: service_healthy

  php-env:  
    build: ./final_project
    volumes:
      - ./final_project/final_project:/var/www/html
      # - ./sites.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 5001:80
    restart: unless-stopped
    depends_on:
      mariadb_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 10s

  mariadb_db:
    image: mariadb:11.7-noble
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: getinplay
    volumes:
      - ./final_project/db/getinplay.sql:/docker-entrypoint-initdb.d/getinplay.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 50
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    depends_on:
      php-env:
        condition: service_healthy
      mariadb_db:
        condition: service_healthy
    environment:
      PMA_HOST: mariadb_db
      PMA_USER: root
      PMA_PASSWORD: root